n = input('Digite algo:')
print('O tipo primitivo desse número é {}'.format(type(n)))
print('Só tem espaços? {} '.format(n.isspace()))
print('É um número?  {} '.format(n.isnumeric()))
print('É alfabético? {} '.format(n.isalpha()))
print('É alfanumérico? {} '.format(n.isalnum()))
print('Está em maiúsculas? {} '.format(n.isupper()))
print('Está em miúsculas? {} '.format(n.islower()))
print('Está capítalizada? {} '.format(n.istitle()))
